# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbdb90f7d3173f5b4478ae7a86ddc15cfcf669bfe033c88f2cf21161bfe5e779236b994ee398896c624bc16407b598cfbe567b1047035e7e202bf1f2eb37f8c

test:
  secret_key_base: 79ea16867bd590e8be132af0a764fac281826c96bb9af46006121111ad5437e0aff50cb64fc4134de1f76bf4b838db2096d61de3d900752c261da76f92452c65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
